### PR TITLE
Fixed study extension not being materialized on update - see https://github.com/EBISPOT/goci/issues/97

### PR DESCRIPTION
**Pull request by tudorgroza**

### CODE REVIEW

**Comment by twhetzel** [comment]
@tudorgroza not sure if you received a notification, but the Test for this method needs updating.

**Comment by tudorgroza** [comment]
@twhetzel - haven't received one. Will look into fixing the failing test.

**Comment by tudorgroza** [comment]
@twhetzel - fix pushed to branch.

**Comment by twhetzel** [comment]
@tudorgroza saving the page, even without any changes to the form content, returns this error:

```
Page: http://localhost:8080/curation/studies/61989706

Message: java.sql.SQLIntegrityConstraintViolationException: ORA-00001: unique constraint (GWAS.STUDY_EXTENSION_PK) violated

Exception detail: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [GWAS.STUDY_EXTENSION_PK]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

Trace: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [GWAS.STUDY_EXTENSION_PK]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:278) at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244) at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521) at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761) at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730) at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:487) at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291) at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:133) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) at com.sun.proxy.$Proxy152.save(Unknown Source) at uk.ac.ebi.spot.goci.curation.service.StudyUpdateService.updateStudy(StudyUpdateService.java:78) at uk.ac.ebi.spot.goci.curation.controller.StudyController.updateStudy(StudyController.java:670) at
```

**Comment by tudorgroza** [comment]
Thanks @twhetzel

**Comment by tudorgroza** [comment]
@twhetzel - had a look and I don't get it. I need a way to either spin up the application against the DEV DB or, your help to send me back some log entries I can add to debug the issue. Would you be able to help with one or the either?

**Comment by twhetzel** [comment]
Sure, let me write back directly with some options.

**Pull request merged**
