### PR TITLE
Fixed ancestry - see https://github.com/EBISPOT/goci/issues/131

### PR DESCRIPTION
**Pull request by tudorgroza**

### CODE REVIEW

**Comment by twhetzel** [comment]
For the "developer" test of the update and before merging the fix, I create a submission with the data to test on the sandbox Deposition app and then import the submission using a local instance of the Curation app running the code from this branch. I am not able to upload a new template for a new submission on the sandbox Depo app since another Depo app update is causing the "Country of Recruitment" to fail validation. See http://193.62.54.159/gwas/deposition/submission/5f1eb52b86621e00017ac15c

**Comment by tudorgroza** [comment]
Just make sure you use a country as per the list provided by the template

**Comment by twhetzel** [comment]
I did and it still failed, e.g. U.K.

**Comment by tudorgroza** [comment]
@twhetzel - in the file associated with the submission above, the country is `U.K` not `U.K.`

**Comment by twhetzel** [comment]
Thanks for spotting the issue in the template. I updated the tests and will merge the PR now.

**Pull request merged**
